apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: local
deploy:
  kubectl:
    manifests:
      - ./infra/local/app/*
build:
  local:
    push: false
  artifacts:
    - image: deep-interview-server-local
      context: server
      docker:
        dockerfile: Dockerfile.local
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: deep-interview-client-local
      context: client
      docker:
        dockerfile: Dockerfile.local
      sync:
        manual:
          - src: "**/*.js"
            dest: .

---
apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: prod
deploy:
  kubectl:
    manifests:
      - ./infra/prod/*
