apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: deep-interview-client-local
          env:
            - name: NEXT_PUBLIC_APP_ID
              valueFrom:
                secretKeyRef:
                  name: "interview-secret"
                  key: appid
            - name: NEXT_PUBLIC_UUID
              valueFrom:
                secretKeyRef:
                  name: "interview-secret"
                  key: uuid
            - name: NEXT_PUBLIC_CLIENT_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: "interview-secret"
                  key: clientHostname
            - name: NEXT_PUBLIC_STUDIOS_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: "interview-secret"
                  key: studiosBaseUrl
          resources:
            limits:
              memory: 521Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
