apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: deep-interview-server-local
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "interview-secret"
                  key: jwt-secret
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  name: "interview-secret"
                  key: appid
            - name: UUID
              valueFrom:
                secretKeyRef:
                  name: "interview-secret"
                  key: uuid
            - name: CLIENT_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: "interview-secret"
                  key: clientHostname
            - name: STUDIOS_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: "interview-secret"
                  key: studiosBaseUrl
            - name: MONGODB_HOSTNAME
              value: mongodb-0.mongodb-headless.database
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: deep_interview_db
            - name: MONGODB_USERNAME
              value: plato
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: interview-secret
                  key: mongodb-password
          resources:
            limits:
              memory: 521Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 5000
      targetPort: 5000
